version: '3.5'

services:
  db:
    image: brunoe/postgres-java-notebooks
    build: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - pg-data:/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432
  notebooks:
    image: brunoe/jupyterjava:develop
    volumes:
      - $PWD:/notebooks
      - $HOME/.m2:/var/maven/.m2
    ports:
      - 8888:8888
    environment:
      MAVEN_CONFIG: '/var/maven/.m2'
      MAVEN_OPTS: '-Duser.home=/var/maven'
    depends_on:
      - db
    links:
      - db

volumes:
  pg-data:

