version: "3.8"

services:
  javanotebook:
        image: brunoe/javanotebook:develop
        environment:
          - SUDO_PASSWORD=password
          - PUID=${UID:?err}
          - PGUID=${GID:?err}
        volumes:
          - "$PWD/notebooks:/notebooks"
          - "$HOME/.m2:/home/user/.m2" 
          - "$PWD/codeserver:/codeserver" 
          - "$PWD/books:/books"        
        ports:
          - "${JUPYTER_PORT-8888}:8888"
          - "${H2_SERVER_PORT-9092}:9092"
  
